-- Enforce NOT NULL on defaulted columns and add missing defaults to match entities
ALTER TABLE contract ALTER COLUMN esignature_status SET DEFAULT 'none';
ALTER TABLE client_interaction ALTER COLUMN interaction_date SET DEFAULT NOW();
ALTER TABLE push_device ALTER COLUMN last_used_at SET DEFAULT NOW();
UPDATE company SET country = DEFAULT WHERE country IS NULL;
ALTER TABLE company ALTER COLUMN country SET NOT NULL;
UPDATE company SET default_vat_rate = DEFAULT WHERE default_vat_rate IS NULL;
ALTER TABLE company ALTER COLUMN default_vat_rate SET NOT NULL;
UPDATE company SET default_margin_factor = DEFAULT WHERE default_margin_factor IS NULL;
ALTER TABLE company ALTER COLUMN default_margin_factor SET NOT NULL;
UPDATE company SET default_retention_rate = DEFAULT WHERE default_retention_rate IS NULL;
ALTER TABLE company ALTER COLUMN default_retention_rate SET NOT NULL;
UPDATE company SET geolocation_enabled = DEFAULT WHERE geolocation_enabled IS NULL;
ALTER TABLE company ALTER COLUMN geolocation_enabled SET NOT NULL;
UPDATE app_user SET overtime_balance_minutes = DEFAULT WHERE overtime_balance_minutes IS NULL;
ALTER TABLE app_user ALTER COLUMN overtime_balance_minutes SET NOT NULL;
UPDATE app_user SET qualifications = DEFAULT WHERE qualifications IS NULL;
ALTER TABLE app_user ALTER COLUMN qualifications SET NOT NULL;
UPDATE app_user SET is_active = DEFAULT WHERE is_active IS NULL;
ALTER TABLE app_user ALTER COLUMN is_active SET NOT NULL;
UPDATE client_contact SET is_primary = DEFAULT WHERE is_primary IS NULL;
ALTER TABLE client_contact ALTER COLUMN is_primary SET NOT NULL;
UPDATE client_interaction SET interaction_date = DEFAULT WHERE interaction_date IS NULL;
ALTER TABLE client_interaction ALTER COLUMN interaction_date SET NOT NULL;
UPDATE client SET country = DEFAULT WHERE country IS NULL;
ALTER TABLE client ALTER COLUMN country SET NOT NULL;
UPDATE client SET pipeline_stage = DEFAULT WHERE pipeline_stage IS NULL;
ALTER TABLE client ALTER COLUMN pipeline_stage SET NOT NULL;
UPDATE canonical_article SET is_composed = DEFAULT WHERE is_composed IS NULL;
ALTER TABLE canonical_article ALTER COLUMN is_composed SET NOT NULL;
UPDATE canonical_article SET observation_count = DEFAULT WHERE observation_count IS NULL;
ALTER TABLE canonical_article ALTER COLUMN observation_count SET NOT NULL;
UPDATE canonical_article SET confidence_classification = DEFAULT WHERE confidence_classification IS NULL;
ALTER TABLE canonical_article ALTER COLUMN confidence_classification SET NOT NULL;
UPDATE canonical_article SET is_active = DEFAULT WHERE is_active IS NULL;
ALTER TABLE canonical_article ALTER COLUMN is_active SET NOT NULL;
UPDATE offer_line SET variant_type = DEFAULT WHERE variant_type IS NULL;
ALTER TABLE offer_line ALTER COLUMN variant_type SET NOT NULL;
UPDATE offer_line SET sort_order = DEFAULT WHERE sort_order IS NULL;
ALTER TABLE offer_line ALTER COLUMN sort_order SET NOT NULL;
UPDATE offer_assumption SET status = DEFAULT WHERE status IS NULL;
ALTER TABLE offer_assumption ALTER COLUMN status SET NOT NULL;
UPDATE offer SET status = DEFAULT WHERE status IS NULL;
ALTER TABLE offer ALTER COLUMN status SET NOT NULL;
UPDATE offer SET version = DEFAULT WHERE version IS NULL;
ALTER TABLE offer ALTER COLUMN version SET NOT NULL;
UPDATE offer SET margin_factor = DEFAULT WHERE margin_factor IS NULL;
ALTER TABLE offer ALTER COLUMN margin_factor SET NOT NULL;
UPDATE offer SET total_ht_cents = DEFAULT WHERE total_ht_cents IS NULL;
ALTER TABLE offer ALTER COLUMN total_ht_cents SET NOT NULL;
UPDATE offer SET total_vat_cents = DEFAULT WHERE total_vat_cents IS NULL;
ALTER TABLE offer ALTER COLUMN total_vat_cents SET NOT NULL;
UPDATE offer SET total_ttc_cents = DEFAULT WHERE total_ttc_cents IS NULL;
ALTER TABLE offer ALTER COLUMN total_ttc_cents SET NOT NULL;
UPDATE offer SET vat_rate = DEFAULT WHERE vat_rate IS NULL;
ALTER TABLE offer ALTER COLUMN vat_rate SET NOT NULL;
UPDATE offer SET validity_days = DEFAULT WHERE validity_days IS NULL;
ALTER TABLE offer ALTER COLUMN validity_days SET NOT NULL;
UPDATE contract_amendment SET amount_delta_cents = DEFAULT WHERE amount_delta_cents IS NULL;
ALTER TABLE contract_amendment ALTER COLUMN amount_delta_cents SET NOT NULL;
UPDATE contract_amendment SET status = DEFAULT WHERE status IS NULL;
ALTER TABLE contract_amendment ALTER COLUMN status SET NOT NULL;
UPDATE contract SET status = DEFAULT WHERE status IS NULL;
ALTER TABLE contract ALTER COLUMN status SET NOT NULL;
UPDATE contract SET retention_rate = DEFAULT WHERE retention_rate IS NULL;
ALTER TABLE contract ALTER COLUMN retention_rate SET NOT NULL;
UPDATE contract SET esignature_provider = DEFAULT WHERE esignature_provider IS NULL;
ALTER TABLE contract ALTER COLUMN esignature_provider SET NOT NULL;
UPDATE contract SET esignature_status = DEFAULT WHERE esignature_status IS NULL;
ALTER TABLE contract ALTER COLUMN esignature_status SET NOT NULL;
UPDATE project_lot SET sort_order = DEFAULT WHERE sort_order IS NULL;
ALTER TABLE project_lot ALTER COLUMN sort_order SET NOT NULL;
UPDATE project_milestone SET status = DEFAULT WHERE status IS NULL;
ALTER TABLE project_milestone ALTER COLUMN status SET NOT NULL;
UPDATE task SET status = DEFAULT WHERE status IS NULL;
ALTER TABLE task ALTER COLUMN status SET NOT NULL;
UPDATE task SET priority = DEFAULT WHERE priority IS NULL;
ALTER TABLE task ALTER COLUMN priority SET NOT NULL;
UPDATE task SET actual_hours = DEFAULT WHERE actual_hours IS NULL;
ALTER TABLE task ALTER COLUMN actual_hours SET NOT NULL;
UPDATE task SET progress_percent = DEFAULT WHERE progress_percent IS NULL;
ALTER TABLE task ALTER COLUMN progress_percent SET NOT NULL;
UPDATE project SET status = DEFAULT WHERE status IS NULL;
ALTER TABLE project ALTER COLUMN status SET NOT NULL;
UPDATE project SET actual_cost_cents = DEFAULT WHERE actual_cost_cents IS NULL;
ALTER TABLE project ALTER COLUMN actual_cost_cents SET NOT NULL;
UPDATE project SET progress_percent = DEFAULT WHERE progress_percent IS NULL;
ALTER TABLE project ALTER COLUMN progress_percent SET NOT NULL;
UPDATE time_entry SET break_minutes = DEFAULT WHERE break_minutes IS NULL;
ALTER TABLE time_entry ALTER COLUMN break_minutes SET NOT NULL;
UPDATE time_entry SET overtime_minutes = DEFAULT WHERE overtime_minutes IS NULL;
ALTER TABLE time_entry ALTER COLUMN overtime_minutes SET NOT NULL;
UPDATE time_entry SET travel_minutes = DEFAULT WHERE travel_minutes IS NULL;
ALTER TABLE time_entry ALTER COLUMN travel_minutes SET NOT NULL;
UPDATE time_entry SET category = DEFAULT WHERE category IS NULL;
ALTER TABLE time_entry ALTER COLUMN category SET NOT NULL;
UPDATE time_entry SET status = DEFAULT WHERE status IS NULL;
ALTER TABLE time_entry ALTER COLUMN status SET NOT NULL;
UPDATE time_entry SET is_offline_entry = DEFAULT WHERE is_offline_entry IS NULL;
ALTER TABLE time_entry ALTER COLUMN is_offline_entry SET NOT NULL;
UPDATE subscription SET saas_seat_count = DEFAULT WHERE saas_seat_count IS NULL;
ALTER TABLE subscription ALTER COLUMN saas_seat_count SET NOT NULL;
UPDATE subscription SET application_seat_count = DEFAULT WHERE application_seat_count IS NULL;
ALTER TABLE subscription ALTER COLUMN application_seat_count SET NOT NULL;
UPDATE expense SET is_billable = DEFAULT WHERE is_billable IS NULL;
ALTER TABLE expense ALTER COLUMN is_billable SET NOT NULL;
UPDATE expense SET status = DEFAULT WHERE status IS NULL;
ALTER TABLE expense ALTER COLUMN status SET NOT NULL;
UPDATE daily_report SET materials_used = DEFAULT WHERE materials_used IS NULL;
ALTER TABLE daily_report ALTER COLUMN materials_used SET NOT NULL;
UPDATE daily_report SET photos = DEFAULT WHERE photos IS NULL;
ALTER TABLE daily_report ALTER COLUMN photos SET NOT NULL;
UPDATE billing_event SET currency = DEFAULT WHERE currency IS NULL;
ALTER TABLE billing_event ALTER COLUMN currency SET NOT NULL;
UPDATE billing_event SET metadata = DEFAULT WHERE metadata IS NULL;
ALTER TABLE billing_event ALTER COLUMN metadata SET NOT NULL;
UPDATE task_dependency SET type = DEFAULT WHERE type IS NULL;
ALTER TABLE task_dependency ALTER COLUMN type SET NOT NULL;
UPDATE task_dependency SET lag_days = DEFAULT WHERE lag_days IS NULL;
ALTER TABLE task_dependency ALTER COLUMN lag_days SET NOT NULL;
UPDATE supplier SET payment_terms_days = DEFAULT WHERE payment_terms_days IS NULL;
ALTER TABLE supplier ALTER COLUMN payment_terms_days SET NOT NULL;
UPDATE purchase_order_line SET delivered_quantity = DEFAULT WHERE delivered_quantity IS NULL;
ALTER TABLE purchase_order_line ALTER COLUMN delivered_quantity SET NOT NULL;
UPDATE purchase_order SET status = DEFAULT WHERE status IS NULL;
ALTER TABLE purchase_order ALTER COLUMN status SET NOT NULL;
UPDATE purchase_order SET total_ht_cents = DEFAULT WHERE total_ht_cents IS NULL;
ALTER TABLE purchase_order ALTER COLUMN total_ht_cents SET NOT NULL;
UPDATE portal_token SET is_active = DEFAULT WHERE is_active IS NULL;
ALTER TABLE portal_token ALTER COLUMN is_active SET NOT NULL;
UPDATE plan_annotation SET color = DEFAULT WHERE color IS NULL;
ALTER TABLE plan_annotation ALTER COLUMN color SET NOT NULL;
UPDATE plan SET version = DEFAULT WHERE version IS NULL;
ALTER TABLE plan ALTER COLUMN version SET NOT NULL;
UPDATE room_type SET typical_articles = DEFAULT WHERE typical_articles IS NULL;
ALTER TABLE room_type ALTER COLUMN typical_articles SET NOT NULL;
UPDATE room_type SET project_count = DEFAULT WHERE project_count IS NULL;
ALTER TABLE room_type ALTER COLUMN project_count SET NOT NULL;
UPDATE room_type SET occurrence_count = DEFAULT WHERE occurrence_count IS NULL;
ALTER TABLE room_type ALTER COLUMN occurrence_count SET NOT NULL;
UPDATE business_rule SET confidence = DEFAULT WHERE confidence IS NULL;
ALTER TABLE business_rule ALTER COLUMN confidence SET NOT NULL;
UPDATE business_rule SET is_active = DEFAULT WHERE is_active IS NULL;
ALTER TABLE business_rule ALTER COLUMN is_active SET NOT NULL;
UPDATE push_device SET is_active = DEFAULT WHERE is_active IS NULL;
ALTER TABLE push_device ALTER COLUMN is_active SET NOT NULL;
UPDATE push_device SET last_used_at = DEFAULT WHERE last_used_at IS NULL;
ALTER TABLE push_device ALTER COLUMN last_used_at SET NOT NULL;
UPDATE notification SET is_read = DEFAULT WHERE is_read IS NULL;
ALTER TABLE notification ALTER COLUMN is_read SET NOT NULL;
UPDATE notification SET push_sent = DEFAULT WHERE push_sent IS NULL;
ALTER TABLE notification ALTER COLUMN push_sent SET NOT NULL;
UPDATE meeting_action SET status = DEFAULT WHERE status IS NULL;
ALTER TABLE meeting_action ALTER COLUMN status SET NOT NULL;
UPDATE site_meeting SET status = DEFAULT WHERE status IS NULL;
ALTER TABLE site_meeting ALTER COLUMN status SET NOT NULL;
UPDATE meeting_attendee SET attendance = DEFAULT WHERE attendance IS NULL;
ALTER TABLE meeting_attendee ALTER COLUMN attendance SET NOT NULL;
UPDATE invoice_line SET sort_order = DEFAULT WHERE sort_order IS NULL;
ALTER TABLE invoice_line ALTER COLUMN sort_order SET NOT NULL;
UPDATE invoice SET status = DEFAULT WHERE status IS NULL;
ALTER TABLE invoice ALTER COLUMN status SET NOT NULL;
UPDATE plus_value SET status = DEFAULT WHERE status IS NULL;
ALTER TABLE plus_value ALTER COLUMN status SET NOT NULL;
UPDATE plus_value SET approved_by_client = DEFAULT WHERE approved_by_client IS NULL;
ALTER TABLE plus_value ALTER COLUMN approved_by_client SET NOT NULL;
UPDATE source_document SET document_type = DEFAULT WHERE document_type IS NULL;
ALTER TABLE source_document ALTER COLUMN document_type SET NOT NULL;
UPDATE source_document SET status = DEFAULT WHERE status IS NULL;
ALTER TABLE source_document ALTER COLUMN status SET NOT NULL;
UPDATE source_document SET total_occurrences = DEFAULT WHERE total_occurrences IS NULL;
ALTER TABLE source_document ALTER COLUMN total_occurrences SET NOT NULL;
UPDATE source_document SET matched_occurrences = DEFAULT WHERE matched_occurrences IS NULL;
ALTER TABLE source_document ALTER COLUMN matched_occurrences SET NOT NULL;
UPDATE source_occurrence SET status = DEFAULT WHERE status IS NULL;
ALTER TABLE source_occurrence ALTER COLUMN status SET NOT NULL;
UPDATE price_observation SET is_outlier = DEFAULT WHERE is_outlier IS NULL;
ALTER TABLE price_observation ALTER COLUMN is_outlier SET NOT NULL;
UPDATE chart_of_accounts SET is_system = DEFAULT WHERE is_system IS NULL;
ALTER TABLE chart_of_accounts ALTER COLUMN is_system SET NOT NULL;
UPDATE chart_of_accounts SET is_active = DEFAULT WHERE is_active IS NULL;
ALTER TABLE chart_of_accounts ALTER COLUMN is_active SET NOT NULL;
UPDATE journal_entry_line SET debit_cents = DEFAULT WHERE debit_cents IS NULL;
ALTER TABLE journal_entry_line ALTER COLUMN debit_cents SET NOT NULL;
UPDATE journal_entry_line SET credit_cents = DEFAULT WHERE credit_cents IS NULL;
ALTER TABLE journal_entry_line ALTER COLUMN credit_cents SET NOT NULL;
UPDATE journal_entry SET is_posted = DEFAULT WHERE is_posted IS NULL;
ALTER TABLE journal_entry ALTER COLUMN is_posted SET NOT NULL;
UPDATE company SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE company ALTER COLUMN created_at SET NOT NULL;
UPDATE company SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE company ALTER COLUMN updated_at SET NOT NULL;
UPDATE app_user SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE app_user ALTER COLUMN created_at SET NOT NULL;
UPDATE app_user SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE app_user ALTER COLUMN updated_at SET NOT NULL;
UPDATE client_contact SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE client_contact ALTER COLUMN created_at SET NOT NULL;
UPDATE client_interaction SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE client_interaction ALTER COLUMN created_at SET NOT NULL;
UPDATE client SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE client ALTER COLUMN created_at SET NOT NULL;
UPDATE client SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE client ALTER COLUMN updated_at SET NOT NULL;
UPDATE project_type SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE project_type ALTER COLUMN created_at SET NOT NULL;
UPDATE canonical_article SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE canonical_article ALTER COLUMN created_at SET NOT NULL;
UPDATE canonical_article SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE canonical_article ALTER COLUMN updated_at SET NOT NULL;
UPDATE offer_line SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE offer_line ALTER COLUMN created_at SET NOT NULL;
UPDATE offer_line SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE offer_line ALTER COLUMN updated_at SET NOT NULL;
UPDATE offer_assumption SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE offer_assumption ALTER COLUMN created_at SET NOT NULL;
UPDATE offer SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE offer ALTER COLUMN created_at SET NOT NULL;
UPDATE offer SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE offer ALTER COLUMN updated_at SET NOT NULL;
UPDATE contract_amendment SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE contract_amendment ALTER COLUMN created_at SET NOT NULL;
UPDATE contract SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE contract ALTER COLUMN created_at SET NOT NULL;
UPDATE contract SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE contract ALTER COLUMN updated_at SET NOT NULL;
UPDATE project_lot SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE project_lot ALTER COLUMN created_at SET NOT NULL;
UPDATE project_milestone SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE project_milestone ALTER COLUMN created_at SET NOT NULL;
UPDATE task SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE task ALTER COLUMN created_at SET NOT NULL;
UPDATE task SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE task ALTER COLUMN updated_at SET NOT NULL;
UPDATE project SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE project ALTER COLUMN created_at SET NOT NULL;
UPDATE project SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE project ALTER COLUMN updated_at SET NOT NULL;
UPDATE expense SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE expense ALTER COLUMN created_at SET NOT NULL;
UPDATE expense SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE expense ALTER COLUMN updated_at SET NOT NULL;
UPDATE subscription SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE subscription ALTER COLUMN created_at SET NOT NULL;
UPDATE subscription SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE subscription ALTER COLUMN updated_at SET NOT NULL;
UPDATE daily_report SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE daily_report ALTER COLUMN created_at SET NOT NULL;
UPDATE daily_report SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE daily_report ALTER COLUMN updated_at SET NOT NULL;
UPDATE billing_event SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE billing_event ALTER COLUMN created_at SET NOT NULL;
UPDATE time_entry SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE time_entry ALTER COLUMN created_at SET NOT NULL;
UPDATE time_entry SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE time_entry ALTER COLUMN updated_at SET NOT NULL;
UPDATE team_member SET joined_at = DEFAULT WHERE joined_at IS NULL;
ALTER TABLE team_member ALTER COLUMN joined_at SET NOT NULL;
UPDATE team SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE team ALTER COLUMN created_at SET NOT NULL;
UPDATE team SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE team ALTER COLUMN updated_at SET NOT NULL;
UPDATE stock_location SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE stock_location ALTER COLUMN created_at SET NOT NULL;
UPDATE vehicle SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE vehicle ALTER COLUMN created_at SET NOT NULL;
UPDATE vehicle SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE vehicle ALTER COLUMN updated_at SET NOT NULL;
UPDATE supplier SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE supplier ALTER COLUMN created_at SET NOT NULL;
UPDATE supplier SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE supplier ALTER COLUMN updated_at SET NOT NULL;
UPDATE stock_item SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE stock_item ALTER COLUMN created_at SET NOT NULL;
UPDATE stock_item SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE stock_item ALTER COLUMN updated_at SET NOT NULL;
UPDATE stock_movement SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE stock_movement ALTER COLUMN created_at SET NOT NULL;
UPDATE purchase_order SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE purchase_order ALTER COLUMN created_at SET NOT NULL;
UPDATE purchase_order SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE purchase_order ALTER COLUMN updated_at SET NOT NULL;
UPDATE purchase_order_line SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE purchase_order_line ALTER COLUMN created_at SET NOT NULL;
UPDATE portal_token SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE portal_token ALTER COLUMN created_at SET NOT NULL;
UPDATE plan_annotation SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE plan_annotation ALTER COLUMN created_at SET NOT NULL;
UPDATE plan SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE plan ALTER COLUMN created_at SET NOT NULL;
UPDATE plan SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE plan ALTER COLUMN updated_at SET NOT NULL;
UPDATE room_type SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE room_type ALTER COLUMN created_at SET NOT NULL;
UPDATE room_type SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE room_type ALTER COLUMN updated_at SET NOT NULL;
UPDATE business_rule SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE business_rule ALTER COLUMN created_at SET NOT NULL;
UPDATE business_rule SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE business_rule ALTER COLUMN updated_at SET NOT NULL;
UPDATE meeting_action SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE meeting_action ALTER COLUMN created_at SET NOT NULL;
UPDATE site_meeting SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE site_meeting ALTER COLUMN created_at SET NOT NULL;
UPDATE site_meeting SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE site_meeting ALTER COLUMN updated_at SET NOT NULL;
UPDATE push_device SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE push_device ALTER COLUMN created_at SET NOT NULL;
UPDATE notification SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE notification ALTER COLUMN created_at SET NOT NULL;
UPDATE invoice_line SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE invoice_line ALTER COLUMN created_at SET NOT NULL;
UPDATE invoice SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE invoice ALTER COLUMN created_at SET NOT NULL;
UPDATE invoice SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE invoice ALTER COLUMN updated_at SET NOT NULL;
UPDATE plus_value SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE plus_value ALTER COLUMN created_at SET NOT NULL;
UPDATE plus_value SET updated_at = DEFAULT WHERE updated_at IS NULL;
ALTER TABLE plus_value ALTER COLUMN updated_at SET NOT NULL;
UPDATE source_document SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE source_document ALTER COLUMN created_at SET NOT NULL;
UPDATE source_occurrence SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE source_occurrence ALTER COLUMN created_at SET NOT NULL;
UPDATE price_observation SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE price_observation ALTER COLUMN created_at SET NOT NULL;
UPDATE article_alias SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE article_alias ALTER COLUMN created_at SET NOT NULL;
UPDATE audit_log SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE audit_log ALTER COLUMN created_at SET NOT NULL;
UPDATE chart_of_accounts SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE chart_of_accounts ALTER COLUMN created_at SET NOT NULL;
UPDATE journal_entry_line SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE journal_entry_line ALTER COLUMN created_at SET NOT NULL;
UPDATE journal_entry SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE journal_entry ALTER COLUMN created_at SET NOT NULL;
UPDATE payment SET created_at = DEFAULT WHERE created_at IS NULL;
ALTER TABLE payment ALTER COLUMN created_at SET NOT NULL;
