-- Tenant-scoped foreign keys: a row may only reference rows of its own company.
-- Plain FK checks ignore RLS, so without these a tenant could link to another tenant's records.
ALTER TABLE app_user ADD CONSTRAINT app_user_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE canonical_article ADD CONSTRAINT canonical_article_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE chart_of_accounts ADD CONSTRAINT chart_of_accounts_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE client ADD CONSTRAINT client_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE contract ADD CONSTRAINT contract_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE invoice ADD CONSTRAINT invoice_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE journal_entry ADD CONSTRAINT journal_entry_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE offer ADD CONSTRAINT offer_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE plan ADD CONSTRAINT plan_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE project ADD CONSTRAINT project_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE project_lot ADD CONSTRAINT project_lot_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE project_type ADD CONSTRAINT project_type_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE purchase_order ADD CONSTRAINT purchase_order_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE room_type ADD CONSTRAINT room_type_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE site_meeting ADD CONSTRAINT site_meeting_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE source_document ADD CONSTRAINT source_document_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE source_occurrence ADD CONSTRAINT source_occurrence_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE stock_item ADD CONSTRAINT stock_item_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE stock_location ADD CONSTRAINT stock_location_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE subscription ADD CONSTRAINT subscription_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE supplier ADD CONSTRAINT supplier_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE task ADD CONSTRAINT task_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE team ADD CONSTRAINT team_company_id_id_key UNIQUE (company_id, id);
ALTER TABLE article_alias ADD CONSTRAINT article_alias_canonical_article_id_tenant_fkey FOREIGN KEY (company_id, canonical_article_id) REFERENCES canonical_article (company_id, id);
ALTER TABLE billing_event ADD CONSTRAINT billing_event_subscription_id_tenant_fkey FOREIGN KEY (company_id, subscription_id) REFERENCES subscription (company_id, id);
ALTER TABLE business_rule ADD CONSTRAINT business_rule_project_type_id_tenant_fkey FOREIGN KEY (company_id, project_type_id) REFERENCES project_type (company_id, id);
ALTER TABLE business_rule ADD CONSTRAINT business_rule_canonical_article_id_tenant_fkey FOREIGN KEY (company_id, canonical_article_id) REFERENCES canonical_article (company_id, id);
ALTER TABLE business_rule ADD CONSTRAINT business_rule_room_type_id_tenant_fkey FOREIGN KEY (company_id, room_type_id) REFERENCES room_type (company_id, id);
ALTER TABLE chart_of_accounts ADD CONSTRAINT chart_of_accounts_parent_id_tenant_fkey FOREIGN KEY (company_id, parent_id) REFERENCES chart_of_accounts (company_id, id);
ALTER TABLE client_contact ADD CONSTRAINT client_contact_client_id_tenant_fkey FOREIGN KEY (company_id, client_id) REFERENCES client (company_id, id);
ALTER TABLE client_interaction ADD CONSTRAINT client_interaction_user_id_tenant_fkey FOREIGN KEY (company_id, user_id) REFERENCES app_user (company_id, id);
ALTER TABLE client_interaction ADD CONSTRAINT client_interaction_client_id_tenant_fkey FOREIGN KEY (company_id, client_id) REFERENCES client (company_id, id);
ALTER TABLE contract ADD CONSTRAINT contract_created_by_tenant_fkey FOREIGN KEY (company_id, created_by) REFERENCES app_user (company_id, id);
ALTER TABLE contract ADD CONSTRAINT contract_client_id_tenant_fkey FOREIGN KEY (company_id, client_id) REFERENCES client (company_id, id);
ALTER TABLE contract ADD CONSTRAINT contract_offer_id_tenant_fkey FOREIGN KEY (company_id, offer_id) REFERENCES offer (company_id, id);
ALTER TABLE contract_amendment ADD CONSTRAINT contract_amendment_contract_id_tenant_fkey FOREIGN KEY (company_id, contract_id) REFERENCES contract (company_id, id);
ALTER TABLE daily_report ADD CONSTRAINT daily_report_project_id_tenant_fkey FOREIGN KEY (company_id, project_id) REFERENCES project (company_id, id);
ALTER TABLE daily_report ADD CONSTRAINT daily_report_user_id_tenant_fkey FOREIGN KEY (company_id, user_id) REFERENCES app_user (company_id, id);
ALTER TABLE expense ADD CONSTRAINT expense_project_id_tenant_fkey FOREIGN KEY (company_id, project_id) REFERENCES project (company_id, id);
ALTER TABLE expense ADD CONSTRAINT expense_approved_by_tenant_fkey FOREIGN KEY (company_id, approved_by) REFERENCES app_user (company_id, id);
ALTER TABLE expense ADD CONSTRAINT expense_task_id_tenant_fkey FOREIGN KEY (company_id, task_id) REFERENCES task (company_id, id);
ALTER TABLE expense ADD CONSTRAINT expense_user_id_tenant_fkey FOREIGN KEY (company_id, user_id) REFERENCES app_user (company_id, id);
ALTER TABLE invoice ADD CONSTRAINT invoice_project_id_tenant_fkey FOREIGN KEY (company_id, project_id) REFERENCES project (company_id, id);
ALTER TABLE invoice ADD CONSTRAINT invoice_created_by_tenant_fkey FOREIGN KEY (company_id, created_by) REFERENCES app_user (company_id, id);
ALTER TABLE invoice ADD CONSTRAINT invoice_reference_invoice_id_tenant_fkey FOREIGN KEY (company_id, reference_invoice_id) REFERENCES invoice (company_id, id);
ALTER TABLE invoice ADD CONSTRAINT invoice_client_id_tenant_fkey FOREIGN KEY (company_id, client_id) REFERENCES client (company_id, id);
ALTER TABLE invoice_line ADD CONSTRAINT invoice_line_invoice_id_tenant_fkey FOREIGN KEY (company_id, invoice_id) REFERENCES invoice (company_id, id);
ALTER TABLE journal_entry ADD CONSTRAINT journal_entry_posted_by_tenant_fkey FOREIGN KEY (company_id, posted_by) REFERENCES app_user (company_id, id);
ALTER TABLE journal_entry ADD CONSTRAINT journal_entry_created_by_tenant_fkey FOREIGN KEY (company_id, created_by) REFERENCES app_user (company_id, id);
ALTER TABLE journal_entry_line ADD CONSTRAINT journal_entry_line_journal_entry_id_tenant_fkey FOREIGN KEY (company_id, journal_entry_id) REFERENCES journal_entry (company_id, id);
ALTER TABLE journal_entry_line ADD CONSTRAINT journal_entry_line_account_id_tenant_fkey FOREIGN KEY (company_id, account_id) REFERENCES chart_of_accounts (company_id, id);
ALTER TABLE meeting_action ADD CONSTRAINT meeting_action_meeting_id_tenant_fkey FOREIGN KEY (company_id, meeting_id) REFERENCES site_meeting (company_id, id);
ALTER TABLE meeting_attendee ADD CONSTRAINT meeting_attendee_meeting_id_tenant_fkey FOREIGN KEY (company_id, meeting_id) REFERENCES site_meeting (company_id, id);
ALTER TABLE notification ADD CONSTRAINT notification_user_id_tenant_fkey FOREIGN KEY (company_id, user_id) REFERENCES app_user (company_id, id);
ALTER TABLE offer ADD CONSTRAINT offer_project_type_id_tenant_fkey FOREIGN KEY (company_id, project_type_id) REFERENCES project_type (company_id, id);
ALTER TABLE offer ADD CONSTRAINT offer_client_id_tenant_fkey FOREIGN KEY (company_id, client_id) REFERENCES client (company_id, id);
ALTER TABLE offer_assumption ADD CONSTRAINT offer_assumption_offer_id_tenant_fkey FOREIGN KEY (company_id, offer_id) REFERENCES offer (company_id, id);
ALTER TABLE offer_line ADD CONSTRAINT offer_line_canonical_article_id_tenant_fkey FOREIGN KEY (company_id, canonical_article_id) REFERENCES canonical_article (company_id, id);
ALTER TABLE offer_line ADD CONSTRAINT offer_line_offer_id_tenant_fkey FOREIGN KEY (company_id, offer_id) REFERENCES offer (company_id, id);
ALTER TABLE payment ADD CONSTRAINT payment_created_by_tenant_fkey FOREIGN KEY (company_id, created_by) REFERENCES app_user (company_id, id);
ALTER TABLE payment ADD CONSTRAINT payment_invoice_id_tenant_fkey FOREIGN KEY (company_id, invoice_id) REFERENCES invoice (company_id, id);
ALTER TABLE payment ADD CONSTRAINT payment_journal_entry_id_tenant_fkey FOREIGN KEY (company_id, journal_entry_id) REFERENCES journal_entry (company_id, id);
ALTER TABLE plan_annotation ADD CONSTRAINT plan_annotation_plan_id_tenant_fkey FOREIGN KEY (company_id, plan_id) REFERENCES plan (company_id, id);
ALTER TABLE plus_value ADD CONSTRAINT plus_value_created_by_tenant_fkey FOREIGN KEY (company_id, created_by) REFERENCES app_user (company_id, id);
ALTER TABLE plus_value ADD CONSTRAINT plus_value_invoice_id_tenant_fkey FOREIGN KEY (company_id, invoice_id) REFERENCES invoice (company_id, id);
ALTER TABLE plus_value ADD CONSTRAINT plus_value_project_id_tenant_fkey FOREIGN KEY (company_id, project_id) REFERENCES project (company_id, id);
ALTER TABLE portal_token ADD CONSTRAINT portal_token_project_id_tenant_fkey FOREIGN KEY (company_id, project_id) REFERENCES project (company_id, id);
ALTER TABLE portal_token ADD CONSTRAINT portal_token_created_by_tenant_fkey FOREIGN KEY (company_id, created_by) REFERENCES app_user (company_id, id);
ALTER TABLE price_observation ADD CONSTRAINT price_observation_canonical_article_id_tenant_fkey FOREIGN KEY (company_id, canonical_article_id) REFERENCES canonical_article (company_id, id);
ALTER TABLE price_observation ADD CONSTRAINT price_observation_source_occurrence_id_tenant_fkey FOREIGN KEY (company_id, source_occurrence_id) REFERENCES source_occurrence (company_id, id);
ALTER TABLE project ADD CONSTRAINT project_contract_id_tenant_fkey FOREIGN KEY (company_id, contract_id) REFERENCES contract (company_id, id);
ALTER TABLE project ADD CONSTRAINT project_manager_id_tenant_fkey FOREIGN KEY (company_id, manager_id) REFERENCES app_user (company_id, id);
ALTER TABLE project ADD CONSTRAINT project_client_id_tenant_fkey FOREIGN KEY (company_id, client_id) REFERENCES client (company_id, id);
ALTER TABLE project_lot ADD CONSTRAINT project_lot_project_id_tenant_fkey FOREIGN KEY (company_id, project_id) REFERENCES project (company_id, id);
ALTER TABLE project_milestone ADD CONSTRAINT project_milestone_project_id_tenant_fkey FOREIGN KEY (company_id, project_id) REFERENCES project (company_id, id);
ALTER TABLE project_milestone ADD CONSTRAINT project_milestone_lot_id_tenant_fkey FOREIGN KEY (company_id, lot_id) REFERENCES project_lot (company_id, id);
ALTER TABLE purchase_order ADD CONSTRAINT purchase_order_project_id_tenant_fkey FOREIGN KEY (company_id, project_id) REFERENCES project (company_id, id);
ALTER TABLE purchase_order ADD CONSTRAINT purchase_order_created_by_tenant_fkey FOREIGN KEY (company_id, created_by) REFERENCES app_user (company_id, id);
ALTER TABLE purchase_order ADD CONSTRAINT purchase_order_supplier_id_tenant_fkey FOREIGN KEY (company_id, supplier_id) REFERENCES supplier (company_id, id);
ALTER TABLE purchase_order_line ADD CONSTRAINT purchase_order_line_purchase_order_id_tenant_fkey FOREIGN KEY (company_id, purchase_order_id) REFERENCES purchase_order (company_id, id);
ALTER TABLE purchase_order_line ADD CONSTRAINT purchase_order_line_canonical_article_id_tenant_fkey FOREIGN KEY (company_id, canonical_article_id) REFERENCES canonical_article (company_id, id);
ALTER TABLE push_device ADD CONSTRAINT push_device_user_id_tenant_fkey FOREIGN KEY (company_id, user_id) REFERENCES app_user (company_id, id);
ALTER TABLE site_meeting ADD CONSTRAINT site_meeting_project_id_tenant_fkey FOREIGN KEY (company_id, project_id) REFERENCES project (company_id, id);
ALTER TABLE site_meeting ADD CONSTRAINT site_meeting_created_by_tenant_fkey FOREIGN KEY (company_id, created_by) REFERENCES app_user (company_id, id);
ALTER TABLE source_document ADD CONSTRAINT source_document_imported_by_tenant_fkey FOREIGN KEY (company_id, imported_by) REFERENCES app_user (company_id, id);
ALTER TABLE source_occurrence ADD CONSTRAINT source_occurrence_source_document_id_tenant_fkey FOREIGN KEY (company_id, source_document_id) REFERENCES source_document (company_id, id);
ALTER TABLE source_occurrence ADD CONSTRAINT source_occurrence_canonical_article_id_tenant_fkey FOREIGN KEY (company_id, canonical_article_id) REFERENCES canonical_article (company_id, id);
ALTER TABLE stock_item ADD CONSTRAINT stock_item_location_id_tenant_fkey FOREIGN KEY (company_id, location_id) REFERENCES stock_location (company_id, id);
ALTER TABLE stock_item ADD CONSTRAINT stock_item_canonical_article_id_tenant_fkey FOREIGN KEY (company_id, canonical_article_id) REFERENCES canonical_article (company_id, id);
ALTER TABLE stock_movement ADD CONSTRAINT stock_movement_project_id_tenant_fkey FOREIGN KEY (company_id, project_id) REFERENCES project (company_id, id);
ALTER TABLE stock_movement ADD CONSTRAINT stock_movement_stock_item_id_tenant_fkey FOREIGN KEY (company_id, stock_item_id) REFERENCES stock_item (company_id, id);
ALTER TABLE stock_movement ADD CONSTRAINT stock_movement_from_location_id_tenant_fkey FOREIGN KEY (company_id, from_location_id) REFERENCES stock_location (company_id, id);
ALTER TABLE stock_movement ADD CONSTRAINT stock_movement_to_location_id_tenant_fkey FOREIGN KEY (company_id, to_location_id) REFERENCES stock_location (company_id, id);
ALTER TABLE stock_movement ADD CONSTRAINT stock_movement_performed_by_tenant_fkey FOREIGN KEY (company_id, performed_by) REFERENCES app_user (company_id, id);
ALTER TABLE task ADD CONSTRAINT task_parent_task_id_tenant_fkey FOREIGN KEY (company_id, parent_task_id) REFERENCES task (company_id, id);
ALTER TABLE task ADD CONSTRAINT task_assigned_to_tenant_fkey FOREIGN KEY (company_id, assigned_to) REFERENCES app_user (company_id, id);
ALTER TABLE task ADD CONSTRAINT task_created_by_tenant_fkey FOREIGN KEY (company_id, created_by) REFERENCES app_user (company_id, id);
ALTER TABLE task ADD CONSTRAINT task_project_id_tenant_fkey FOREIGN KEY (company_id, project_id) REFERENCES project (company_id, id);
ALTER TABLE task ADD CONSTRAINT task_lot_id_tenant_fkey FOREIGN KEY (company_id, lot_id) REFERENCES project_lot (company_id, id);
ALTER TABLE team ADD CONSTRAINT team_leader_id_tenant_fkey FOREIGN KEY (company_id, leader_id) REFERENCES app_user (company_id, id);
ALTER TABLE team_member ADD CONSTRAINT team_member_team_id_tenant_fkey FOREIGN KEY (company_id, team_id) REFERENCES team (company_id, id);
ALTER TABLE team_member ADD CONSTRAINT team_member_user_id_tenant_fkey FOREIGN KEY (company_id, user_id) REFERENCES app_user (company_id, id);
ALTER TABLE time_entry ADD CONSTRAINT time_entry_user_id_tenant_fkey FOREIGN KEY (company_id, user_id) REFERENCES app_user (company_id, id);
ALTER TABLE time_entry ADD CONSTRAINT time_entry_task_id_tenant_fkey FOREIGN KEY (company_id, task_id) REFERENCES task (company_id, id);
ALTER TABLE time_entry ADD CONSTRAINT time_entry_approved_by_tenant_fkey FOREIGN KEY (company_id, approved_by) REFERENCES app_user (company_id, id);
ALTER TABLE time_entry ADD CONSTRAINT time_entry_project_id_tenant_fkey FOREIGN KEY (company_id, project_id) REFERENCES project (company_id, id);
ALTER TABLE vehicle ADD CONSTRAINT vehicle_stock_location_id_tenant_fkey FOREIGN KEY (company_id, stock_location_id) REFERENCES stock_location (company_id, id);
ALTER TABLE vehicle ADD CONSTRAINT vehicle_assigned_project_id_tenant_fkey FOREIGN KEY (company_id, assigned_project_id) REFERENCES project (company_id, id);
ALTER TABLE vehicle ADD CONSTRAINT vehicle_assigned_team_id_tenant_fkey FOREIGN KEY (company_id, assigned_team_id) REFERENCES team (company_id, id);
ALTER TABLE team_member ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_member FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON team_member FOR ALL
  USING (company_id = app_current_company_id() OR app_rls_bypass())
  WITH CHECK (company_id = app_current_company_id() OR app_rls_bypass());
